import React from 'react';

export const metadata = {
  title: "SunCart  profile ",
  description: "Generated by create next app",
};

const ProfilePage = () => {
    return (
        <div>
            profile page 
        </div>
    );
};

export default ProfilePage;